title: Ian Maywar
description: Portfolio
theme: jekyll-theme-slate
markdown: kramdown

# Prevent readme from being used to build site
readme_index:
  enabled: false

# Disable GitHub links
github:
  is_project_page: false

sub { vertical-align: sub; font-size: 0.75em; }
